core/urls.py
from django import views
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include
from core.views import generate_report, add_to_cart, add_to_wishlist, ajax_add_review, ajax_contact_form, cart_view, \
    category_list_view, category_product_list__view, checkout_view, customer_dashboard, delete_item_from_cart, \
    filter_product, index, make_address_default, order_detail, payment_completed_view, payment_failed_view, \
    product_detail_view, product_list_view, remove_wishlist, search_view, sign_in, tag_list, update_cart, \
    vendor_detail_view, vendor_list_view, wishlist_view, contact, about_us, privacy_policy, terms_of_service, sign_in, \
    sign_up, change_password, search_characters

app_name = "core"

urlpatterns = [

    # Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product-list"),
    path("product/<pid>/", product_detail_view, name="product-detail"),

    # Category
    path("category/", category_list_view, name="category-list"),
    path("category/", category_list_view, name="category-list"),
    path("category/<cid>/", category_product_list__view, name="category-product-list"),

    # Vendor
    path("vendors/", vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", vendor_detail_view, name="vendor-detail"),

    # Tags
    path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),

    # Add Review
    path("ajax-add-review/<int:pid>/", ajax_add_review, name="ajax-add-review"),

    # Search
    path("search/", search_view, name="search"),
    path('search_characters/', search_characters, name='search_characters'),

    # Filter product URL
    path("filter-products/", filter_product, name="filter-product"),

    # Add to cart URL
    path("add-to-cart/", add_to_cart, name="add-to-cart"),

    # Cart Page URL
    path("cart/", cart_view, name="cart"),

    # Delete ITem from Cart
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),

    # Update  Cart
    path("update-cart/", update_cart, name="update-cart"),

    # Checkout  URL
    path("checkout/", checkout_view, name="checkout"),

    # Paypal URL
    path('paypal/', include('paypal.standard.ipn.urls')),

    # Payment Successful
    path("payment-completed/", payment_completed_view, name="payment-completed"),

    # Payment Failed
    path("payment-failed/", payment_failed_view, name="payment-failed"),

    # Dahboard URL
    path("dashboard/", customer_dashboard, name="dashboard"),

    # Order Detail URL
    path("dashboard/order/<int:id>", order_detail, name="order-detail"),

    # Making address default
    path("make-default-address/", make_address_default, name="make-default-address"),

    # wishlist page
    path("wishlist/", wishlist_view, name="wishlist"),

    # adding to wishlist
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),

    # Remvoing from wishlist
    path("remove-from-wishlist/", remove_wishlist, name="remove-from-wishlist"),

    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact_form, name="ajax-contact-form"),

    path("about_us/", about_us, name="about_us"),
    path("privacy_policy/", privacy_policy, name="privacy_policy"),
    path("terms_of_service/", terms_of_service, name="terms_of_service"),

    # Redirecting to sign-in page
    path("sign-in/", sign_in, name="sign_in"),

    # Redirecting to sign-up page
    path("sign-up/", sign_up, name="sign_up"),

    path('generate-report/', generate_report, name='generate_report'),

    # Change password
    path('change-password/', change_password, name='change-password'),
]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),

    # path("ckeditor/", include("ckeditor_uploader.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path('send-otp/', views.send_otp_view, name='send_otp'),
    path('verify-otp/', views.verify_otp_view, name='verify_otp'),
    path("profile/update/", views.profile_update, name="profile-update"),
    path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('send_forgot_otp/', views.send_forgot_otp_view, name='send_forgot_otp'),
]

userauths/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import AbstractUser 
from django.db.models.signals import post_save


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class TempUser(models.Model):
    email = models.EmailField(unique=True)
    otp = models.CharField(max_length=100)

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image")
    full_name = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200) # +234 (456) - 789
    verified = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.user.username} - {self.full_name} - {self.bio}"


class ContactUs(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200) # +234 (456) - 789
    subject = models.CharField(max_length=200) # +234 (456) - 789
    message = models.TextField()

    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"

    def __str__(self):
        return self.full_name

    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

 
post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)    

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User, Profile


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Username"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email"}))
    otp = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"OTP"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password"}))

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Full Name"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Bio"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Phone"}))

    class Meta:
        model = Profile
        fields = ['full_name', 'image', 'bio', 'phone']

userauths/views.py
import random
import string

from django.contrib.auth.forms import PasswordResetForm
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import redirect, render
from userauths.forms import UserRegisterForm, ProfileForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from userauths.models import Profile, User, TempUser


# User = settings.AUTH_USER_MODEL

def generate_otp(length=6):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))


def send_verification_email(email, otp):
    subject = 'Email Verification'
    message = f'Dear user,\n\nYour One-Time Password (OTP) for account verification is: {otp}\n\nPlease use this OTP for account verification process.\n\nDo not share this OTP with anyone for security reasons.'
    from_email = 'alicart.eshop@gmail.com'  # Update with your email address
    to_email = email
    try:
        send_mail(subject, message, from_email, [to_email])
        return True
    except Exception as e:
        print("Error sending email:", e)
        return False


def send_otp_view(request):
    if request.method == "POST":
        email = request.POST.get('email')
        if TempUser.objects.filter(email=email).exists():
            return JsonResponse({"error": "Email already exists"})
        if User.objects.filter(email=email).exists():
            return JsonResponse({"error": "Email already exists"})
        # Generate OTP
        otp = generate_otp()
        if send_verification_email(email, otp):
            TempUser.objects.create(email=email, otp=otp)
            # Return success response
            return JsonResponse({"success": "OTP has been sent successfully"})
        else:
            return JsonResponse({"error": "OTP not sent, Try again."})
    else:
        return JsonResponse({"error": "Invalid request method"})


def verify_otp_view(request):
    if request.method == "POST":
        email = request.POST.get('email')
        otp = request.POST.get('otp')
        # Retrieve TempUser object based on email
        try:
            temp_user = TempUser.objects.get(email=email)
        except TempUser.DoesNotExist:
            return JsonResponse({"error": "No such user found"})
        # Check if OTP matches
        if temp_user.otp == otp:
            # OTP verification successful, delete TempUser and return success response
            temp_user.delete()
            return JsonResponse({"success": "OTP has been verified successfully"})
        else:
            return JsonResponse({"error": "Invalid OTP"})
    else:
        return JsonResponse({"error": "Invalid request method"})


def register_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey you are already Logged In.")
        return redirect("core:index")
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password1'])  # Set password
            new_user.save()
            # Authenticate and login the user
            new_user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password1'])
            login(request, new_user)
            messages.success(request, f"Hey {new_user.username}, Your account was created successfully.")
            return redirect("core:index")
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, "userauths/sign-up.html", context)


def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey you are already Logged In.")
        return redirect("core:index")
    
    if request.method == "POST":
        email = request.POST.get("email") # peanuts@gmail.com
        password = request.POST.get("password") # getmepeanuts
        try:
            user = User.objects.get(email=email)
            user = authenticate(username=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in.")
                # Clear the session data after login
                if 'wishlist_count' in request.session:
                    if request.session['wishlist_count']:
                        del request.session['wishlist_count']
                if 'cart_data_obj' in request.session:
                    if request.session['cart_data_obj']:
                        del request.session['cart_data_obj']
                return redirect("core:index")
            else:
                messages.warning(request, "User Does Not Exist, create an account.")
    
        except:
            messages.warning(request, f"User with {email} does not exist")
    
    return render(request, "userauths/sign-in.html")


def logout_view(request):
    logout(request)
    messages.success(request, "You logged out.")
    return redirect("userauths:sign-in")


def profile_update(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, "Profile Updated Successfully.")
            return redirect("core:dashboard")
    else:
        form = ProfileForm(instance=profile)

    context = {
        "form": form,
        "profile": profile,
    }

    return render(request, "userauths/profile-edit.html", context)


def forgot_password(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey you are already Logged In.")
        return redirect("core:index")
    if request.method == "POST":
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        otp = request.POST.get('otp')

        # Store the form data in a dictionary to pass it back in case of errors
        form_data = {'email': email, 'password1': password1, 'password2': password2, 'otp': otp}

        if email and password1 and password1 == password2:
            try:
                # Get the user object associated with the provided email
                user = User.objects.get(email=email)

                # Set the new password
                user.set_password(password1)
                user.save()

                # Authenticate and login the user with the new password
                user = authenticate(username=email, password=password1)
                login(request, user)

                # Redirect to the index page
                messages.success(request, f"Hey {user.username}, Your password is changed successfully.")
                return redirect("core:index")
            except User.DoesNotExist:
                # Handle case where user with provided email doesn't exist
                messages.error(request, "User with this email doesn't exist.")
        else:
            # Handle case where email or passwords are missing or passwords don't match
            messages.error(request, "Invalid email or passwords don't match.")

        # Pass form_data along with the error message in the context
        context = {'form_data': form_data}
        return render(request, "userauths/forgot-password.html", context)
    else:
        return render(request, "userauths/forgot-password.html")


def send_forgot_otp_view(request):
    if request.method == "POST":
        email = request.POST.get('email')
        if not User.objects.filter(email=email).exists():
            return JsonResponse({"error": "There is no account associated with this email address."})
        # Generate OTP
        otp = generate_otp()
        if send_verification_email(email, otp):
            TempUser.objects.create(email=email, otp=otp)
            # Return success response
            return JsonResponse({"success": "OTP has been sent successfully"})
        else:
            return JsonResponse({"error": "OTP not sent, Try again."})
    else:
        return JsonResponse({"error": "Invalid request method"})

templates/userauths/forgot-password.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <div id="successMessage" class="alert alert-success" style="display: none;"></div>
                                            <div id="errorMessage" class="alert alert-danger" style="display: none;"></div>

                                            <h1 class="mb-5">Forgot Password</h1>
                                            <p class="mb-30">Don't have an account? <a href="{% url 'userauths:sign-up' %}">Create here</a></p>
                                        </div>
                                        <form id="forgotForm" method="POST">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="email" required name="email" placeholder="Email *" value="{{ form_data.email }}"/>
                                            </div>
                                            <div class="form-group" id="submitBtn">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" id="sendOTPBtn">Reset Password</button>
                                            </div>
                                            <div class="form-group" id="otpField" style="display: none;">
                                                <input type="text" required name="otp" placeholder="OTP *" value="{{ form_data.otp }}"/>
                                            </div>
                                            <div class="form-group" id="verifyBtn" style="display: none;">
                                                <button type="submit" class="btn btn-fill-out btn-block hover-up font-weight-bold" id="verifyOTPBtn">Verify OTP</button>
                                            </div>
                                            <div id="forgotFields" style="display: none;">
                                                <div class="form-group">
                                                    <input type="password" required name="password1" placeholder="New Password *" value="{{ form_data.password1 }}" />
                                                </div>
                                                <div class="form-group">
                                                    <input type="password" required name="password2" placeholder="Confirm Password *" value="{{ form_data.password2 }}" />
                                                </div>
                                            </div>
                                            <div class="form-group mb-30" id="updatePasswordBtn" style="display: none;">
                                                <button type="submit" class="btn btn-fill-out btn-block hover-up font-weight-bold" name="signup">Update Password</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
<script>
    $(document).ready(function(){
        $("#sendOTPBtn").click(function(){
            var email = $("input[name='email']").val();
            if(email.trim() === "") {
                // Show error message or handle empty email scenario
                return;
            }

            $.ajax({
                url: "{% url 'userauths:send_forgot_otp' %}",
                type: "POST",
                data: {
                    'email': email,
                    'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']").val()
                },
                dataType: 'json',
                success: function(data){
                    if (data.error) {
                        $("#errorMessage").text(data.error);
                        $("#errorMessage").show();
                        setTimeout(function(){
                            $("#errorMessage").hide();
                        }, 5000);
                    } else {
                        $("#successMessage").text(data.success);
                        $("#successMessage").show();
                        setTimeout(function(){
                            $("#successMessage").hide();
                        }, 5000);
                        $("#otpField").show();
                        $("#submitBtn").hide();
                        $("#verifyBtn").show();
                    }
                }
            });
        });

        $("#verifyOTPBtn").click(function(){
            var email = $("input[name='email']").val();
            var otp = $("input[name='otp']").val();
            $.ajax({
                url: "{% url 'userauths:verify_otp' %}",
                type: "POST",
                data: {
                    'email': email,
                    'otp': otp,
                    'csrfmiddlewaretoken': $("input[name='csrfmiddlewaretoken']").val()
                },
                dataType: 'json',
                success: function(data){
                    if (data.error) {
                        $("#errorMessage").text(data.error);
                        $("#errorMessage").show();
                        setTimeout(function(){
                            $("#errorMessage").hide();
                        }, 5000);
                    } else {
                        $("#successMessage").text(data.success);
                        $("#successMessage").show();
                        setTimeout(function(){
                            $("#successMessage").hide();
                        }, 5000);
                        $("#verifyBtn").hide();
                        $("#forgotFields").show();
                        $("#updatePasswordBtn").show();
                    }
                }
            });
        });
    });
</script>
{% if messages %}
    <script>
        $("#sendOTPBtn").hide();
        $("#otpField, #forgotFields, #updatePasswordBtn").show();
    </script>
{% endif %}
{% endblock content %}

templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Login</h1>
                                            <p class="mb-30">Don't have an account? <a href="{% url 'userauths:sign-up' %}">Create here</a></p>
                                        </div>
                                        <form method="POST"> 
                                            {% csrf_token %}

                                            <div class="form-group">
                                                <input type="text" required name="email" placeholder="Username or Email *" />
                                            </div>
                                            <div class="form-group">
                                                <input required type="password" name="password" placeholder="Your password *" />
                                            </div>
                                            <!-- <div class="login_footer form-group">
                                                <div class="chek-form">
                                                    <input type="text" required="" name="email" placeholder="Security code *" />
                                                </div>
                                                <span class="security-code">
                                                    <b class="text-new">8</b>
                                                    <b class="text-hot">6</b>
                                                    <b class="text-sale">7</b>
                                                    <b class="text-best">5</b>
                                                </span>
                                            </div> -->
                                            <div class="login_footer form-group mb-50">
                                                <div class="chek-form">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                                        <label class="form-check-label" for="exampleCheckbox1"><span>Remember me</span></label>
                                                    </div>
                                                </div>
                                                <a class="text-muted" href="{% url 'userauths:forgot-password' %}">Forgot password?</a>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Log in</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content %}